const COUNTER_ADD = 'COUNTER_ADD'
const COUNTER_RESET = 'COUNTER_RESET'
const COUNTER_SET = 'COUNTER_SET'

export const COUNTER_ADD2 = 'COUNTER_ADD'
export const COUNTER_RESET2 = 'COUNTER_RESET'
export const COUNTER_SET2 = 'COUNTER_SET'

export default {
  COUNTER_ADD,
  COUNTER_RESET,
  COUNTER_SET
}